apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pawhome

resources:
  - namespace-pawhome.yaml
  - postgres-secret.yaml
  - db-init-configmap.yaml
  - postgres-statefulset-pvc-service.yaml
  - web-deployment-service.yaml
